export type Lesson = { slug: string; title: string; category: string; intro: string; sections: { title: string; text: string }[]; activity: string; takeaway: string };
export const lessons: Lesson[] = [
 { slug: 'construcao-sustentavel', title: 'Como uma construção pode ser sustentável?', category: 'Primeiros passos', intro: 'Uma construção faz parte do ambiente. Ela usa materiais, água e energia e influencia a vida de quem está dentro e ao redor.', sections: [ { title: 'Pensar no ciclo inteiro', text: 'Sustentabilidade começa antes da obra: escolha do terreno, planejamento e materiais. Continua durante a construção, o uso, a manutenção e o destino dos resíduos. Uma solução precisa fazer sentido para o lugar e para as pessoas.' }, { title: 'Conforto também importa', text: 'Um espaço deve ser saudável e confortável. Luz, ventilação, sombra, acústica e acessibilidade ajudam a criar ambientes melhores. Economizar recursos não deve comprometer a segurança.' } ], activity: 'Desenhe a sua sala de aula. Marque por onde entram luz e ar e onde você sente mais calor. Compare as observações com seus colegas.', takeaway: 'Uma boa solução considera ambiente, pessoas e duração.' },
 { slug: 'casa-sustentavel', title: 'Como tornar minha casa mais sustentável?', category: 'No cotidiano', intro: 'Observar o que já existe é o primeiro passo. Pequenas mudanças no uso da casa podem reduzir desperdícios.', sections: [ { title: 'Comece pelos hábitos', text: 'Apague luzes de ambientes vazios, aproveite a claridade quando ela é suficiente e observe torneiras que continuam pingando. Avise um adulto sobre vazamentos e problemas elétricos.' }, { title: 'Planeje antes de mudar', text: 'Sombra e ventilação dependem do clima, da orientação e da construção. Reformas e instalações devem ser avaliadas por profissionais responsáveis. Não improvise sistemas elétricos ou estruturais.' } ], activity: 'Com um adulto, registre três desperdícios e uma ação simples para cada um. Observe o que mudou durante uma semana.', takeaway: 'Uso consciente e manutenção fazem parte da sustentabilidade.' },
 { slug: 'escola-sustentavel', title: 'Como tornar minha escola mais sustentável?', category: 'Na escola', intro: 'A escola é um lugar para aprender e experimentar o cuidado com os recursos de forma coletiva.', sections: [ { title: 'Conheça o espaço', text: 'Observe pátios, salas e corredores. Há sombra? As janelas podem ser usadas com segurança? Existem áreas de solo exposto? Registre as perguntas sem fazer alterações no espaço.' }, { title: 'Uma ação que continua', text: 'Escolha uma melhoria viável com professores e gestão. Defina quem acompanha, como cuidar e como avaliar. Uma horta ou jardim precisa de manutenção e participação, além da implantação.' } ], activity: 'Use o checklist “Minha escola é sustentável?” e escolha um tema para discutir com a turma.', takeaway: 'A comunidade escolar participa da escolha e do cuidado.' },
 { slug: 'caminho-da-agua', title: 'De onde vem a água que usamos?', category: 'Água e território', intro: 'A água percorre um caminho antes de chegar à torneira. Esse caminho liga a cidade aos rios, nascentes e áreas de proteção.', sections: [ { title: 'Da natureza à torneira', text: 'Em muitos sistemas urbanos, a água é captada em mananciais, tratada, armazenada e distribuída. As etapas variam conforme o sistema local. Conhecer o abastecimento da sua cidade ajuda a entender essa relação.' }, { title: 'O cuidado começa no território', text: 'Resíduos, esgoto sem tratamento e degradação do solo podem afetar a água. Preservar vegetação e evitar descarte incorreto protege o ambiente. Água transparente não é necessariamente própria para beber.' } ], activity: 'Pesquise com o professor qual sistema abastece o bairro e desenhe o caminho da água até a escola.', takeaway: 'Cuidar da água também é cuidar do lugar de onde ela vem.' },
 { slug: 'agua-da-chuva', title: 'O que acontece com a água da chuva?', category: 'Água e território', intro: 'Ao cair, a chuva pode infiltrar no solo, ser absorvida por plantas ou escoar pelas superfícies.', sections: [ { title: 'Superfícies mudam o caminho', text: 'Asfalto e concreto reduzem a infiltração. A água pode escoar rapidamente e se acumular onde a drenagem não dá conta. Solo, vegetação e soluções bem dimensionadas podem ajudar a distribuir esse fluxo.' }, { title: 'Reaproveitamento com cuidado', text: 'A água de chuva pode atender usos não potáveis quando existe um sistema adequado, com filtragem, armazenamento protegido, identificação e manutenção. Não deve ser consumida sem tratamento e avaliação apropriados.' } ], activity: 'Observe o pátio depois da chuva, sem entrar em áreas alagadas. Onde a água acumula? Quais superfícies deixam infiltrar?', takeaway: 'A chuva precisa de caminhos planejados.' },
 { slug: 'permeabilidade', title: 'O que é uma área permeável?', category: 'Solo e cidade', intro: 'É uma superfície que permite a entrada de água no solo. O comportamento depende do material, do solo e da manutenção.', sections: [ { title: 'Nem toda superfície funciona igual', text: 'Terra com vegetação e pisos permeáveis podem permitir infiltração. Solo compactado, sujeira e saturação podem limitar esse processo. Permeabilidade não elimina, sozinha, o risco de alagamento.' }, { title: 'Mais verde, mais possibilidades', text: 'Jardins de chuva recebem e retêm parte do escoamento de superfícies próximas. Sua implantação exige avaliação de solo, localização, capacidade e manutenção para funcionar com segurança.' } ], activity: 'Com supervisão, compare a passagem de pequenas quantidades de água por areia e uma superfície impermeável em recipientes. Observe sem concluir que o modelo reproduz toda uma cidade.', takeaway: 'Infiltração, retenção e drenagem trabalham juntas.' },
 { slug: 'ventilacao-natural', title: 'Por que ventilação natural importa?', category: 'Conforto e energia', intro: 'O movimento do ar pode contribuir para o conforto e a renovação do ar em ambientes adequadamente planejados.', sections: [ { title: 'O ar precisa de entrada e saída', text: 'Aberturas em posições diferentes podem criar caminhos para o ar. A ventilação depende do vento, da temperatura, do tamanho das aberturas e de obstáculos ao redor.' }, { title: 'Observe o contexto', text: 'Ruído, poluição, chuva e segurança também influenciam o uso das janelas. Ventilação natural não substitui toda necessidade de climatização ou controle da qualidade do ar.' } ], activity: 'Desenhe setas mostrando caminhos possíveis para o ar na sala. Compare a sensação de conforto em horários diferentes.', takeaway: 'Conforto depende de projeto e das condições do lugar.' },
 { slug: 'luz-natural', title: 'Como aproveitar iluminação natural?', category: 'Conforto e energia', intro: 'A luz do dia pode tornar os espaços mais agradáveis e reduzir o uso de iluminação artificial quando atende à atividade.', sections: [ { title: 'Claridade sem ofuscamento', text: 'Luz em excesso e sol direto podem dificultar a visão e aquecer a sala. Distribuir a claridade e prever sombra são escolhas tão importantes quanto abrir uma janela.' }, { title: 'Cada atividade tem uma necessidade', text: 'Ler, desenhar e circular exigem condições diferentes. Cortinas, disposição das mesas e manutenção das aberturas influenciam a experiência, respeitando as orientações da escola.' } ], activity: 'Observe sua mesa em três momentos do dia. Anote onde é mais fácil ler e onde aparecem reflexos.', takeaway: 'Aproveitar a luz é equilibrar claridade, sombra e conforto.' },
 { slug: 'materiais', title: 'De onde vêm os materiais de uma construção?', category: 'Materiais e resíduos', intro: 'Cimento, areia, madeira, metais e vidro têm histórias de extração, produção, transporte e uso.', sections: [ { title: 'Olhe além da aparência', text: 'Impactos dependem de origem, fabricação, distância de transporte, durabilidade e destino final. Um material não é sustentável apenas por ter a cor verde ou conter uma parte reciclada.' }, { title: 'Durar e manter', text: 'Escolher o material adequado à função e prever manutenção reduz substituições e desperdícios. Desempenho e segurança precisam ser demonstrados, especialmente em aplicações estruturais.' } ], activity: 'Escolha três materiais da sua escola e pesquise suas origens, usos e possibilidades de recuperação.', takeaway: 'A escolha de materiais considera todo o ciclo de vida.' },
 { slug: 'residuo-material', title: 'Resíduo pode virar material?', category: 'Materiais e resíduos', intro: 'Reutilizar e reciclar materiais pode reduzir desperdícios, mas exige separação, cuidado e avaliação técnica.', sections: [ { title: 'Reutilizar e reciclar são diferentes', text: 'Reutilizar é usar novamente um produto ou componente. Reciclar envolve transformar o material. Ambas as estratégias dependem de condições adequadas e não justificam gerar mais resíduos.' }, { title: 'Pesquisa antes da aplicação', text: 'O estudo Casa da Terra, associado à UNIFEI, ilustra a investigação de vidro moído em solo-cimento. Ensaios ajudam a entender resistência e absorção. O comportamento depende da mistura e do processo.' } ], activity: 'Monte um mapa: objeto → resíduo → possível novo uso → o que precisa ser testado. Não manipule vidro quebrado.', takeaway: 'Reaproveitamento precisa caminhar com segurança e evidências.' },
 { slug: 'engenharia-ambiente', title: 'O que a Engenharia Civil tem a ver com o meio ambiente?', category: 'Engenharia e sociedade', intro: 'A Engenharia Civil participa das decisões sobre edifícios, água, infraestrutura, mobilidade e uso do território.', sections: [ { title: 'Decisões que deixam marcas', text: 'Uma obra pode consumir recursos e gerar resíduos, mas seu planejamento também pode reduzir impactos e melhorar o acesso a espaços e serviços. A decisão técnica tem consequências sociais e ambientais.' }, { title: 'Aprender com a comunidade', text: 'Na extensão universitária, o conhecimento acadêmico encontra experiências e necessidades do território. Ouvir a escola é parte da construção de uma atividade relevante, acessível e duradoura.' } ], activity: 'Liste um problema ambiental que você observa no bairro. Que perguntas um engenheiro e a comunidade precisariam responder juntos?', takeaway: 'Engenharia serve às pessoas e ao ambiente em que elas vivem.' }
];
export const checklistItems = [
 ['luz', 'Luz natural', 'As salas aproveitam a claridade sem reflexos que dificultem a leitura?'],
 ['ar', 'Ventilação', 'O ar pode circular com segurança e conforme as condições do ambiente?'],
 ['verde', 'Áreas verdes', 'Há vegetação e sombra, com cuidado e manutenção?'],
 ['solo', 'Permeabilidade', 'Existem áreas onde a água pode infiltrar no solo?'],
 ['agua', 'Água', 'Vazamentos são comunicados e o consumo é acompanhado?'],
 ['residuos', 'Resíduos', 'A escola separa resíduos de acordo com a coleta disponível?'],
 ['energia', 'Energia', 'Luzes e equipamentos são desligados quando não são necessários?'],
 ['materiais', 'Materiais', 'Materiais em bom estado são reutilizados antes de serem descartados?'],
 ['conforto', 'Conforto ambiental', 'A turma conversa sobre calor, ruído e condições para aprender?']
] as const;
export const quizQuestions = [
 { question: 'Qual superfície pode favorecer a infiltração da água?', options: ['Pátio completamente asfaltado', 'Solo com vegetação em boas condições', 'Laje de concreto'], answer: 1, explanation: 'O solo com vegetação pode permitir infiltração. Compactação, saturação e características locais influenciam o resultado.' },
 { question: 'Vidro moído sempre melhora um tijolo?', options: ['Sim, em qualquer quantidade', 'Só depende da cor do vidro', 'Não: a mistura e os ensaios precisam ser avaliados'], answer: 2, explanation: 'O desempenho depende da dosagem, do processo e da propriedade avaliada. Resistência e absorção podem apresentar comportamentos diferentes.' },
 { question: 'A água da chuva armazenada pode ser bebida diretamente?', options: ['Não, exige tratamento e avaliação adequada', 'Sim, se parecer transparente', 'Sim, depois de um dia'], answer: 0, explanation: 'A aparência não garante potabilidade. Sistemas de aproveitamento para usos não potáveis precisam de proteção e manutenção.' },
 { question: 'Qual é o primeiro passo para uma ação sustentável na escola?', options: ['Comprar equipamentos imediatamente', 'Observar o espaço e ouvir a comunidade', 'Copiar uma solução de outra cidade'], answer: 1, explanation: 'Cada escola tem um contexto. Observar e ouvir ajuda a escolher ações viáveis e relevantes.' }
];
